"""Add LaporanRehabilitasi and LaporanGerakanHasil models

Revision ID: 57492ae4621a
Revises: 846541daadc9
Create Date: 2025-06-05 16:47:55.060975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57492ae4621a'
down_revision = '846541daadc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laporan_rehabilitasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_rehabilitasi_id', sa.Integer(), nullable=True),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.Column('terapis_id', sa.Integer(), nullable=True),
    sa.Column('tanggal_laporan', sa.Date(), nullable=False),
    sa.Column('total_waktu_rehabilitasi_detik', sa.Integer(), nullable=True),
    sa.Column('catatan_pasien_laporan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_rehabilitasi_id'], ['program_rehabilitasi.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['terapis_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laporan_gerakan_hasil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laporan_rehabilitasi_id', sa.Integer(), nullable=False),
    sa.Column('gerakan_id', sa.Integer(), nullable=True),
    sa.Column('program_gerakan_detail_id_asli', sa.Integer(), nullable=True),
    sa.Column('urutan_gerakan_dalam_program', sa.Integer(), nullable=True),
    sa.Column('jumlah_sempurna', sa.Integer(), nullable=True),
    sa.Column('jumlah_tidak_sempurna', sa.Integer(), nullable=True),
    sa.Column('jumlah_tidak_terdeteksi', sa.Integer(), nullable=True),
    sa.Column('waktu_aktual_per_gerakan_detik', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerakan_id'], ['gerakan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['laporan_rehabilitasi_id'], ['laporan_rehabilitasi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_gerakan_detail_id_asli'], ['program_gerakan_detail.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan_gerakan_hasil')
    op.drop_table('laporan_rehabilitasi')
    # ### end Alembic commands ###
