"""Add Gerakan, ProgramRehabilitasi, ProgramGerakanDetail models

Revision ID: 846541daadc9
Revises: 9ba9d9d0d890
Create Date: 2025-06-05 16:30:23.384120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846541daadc9'
down_revision = '9ba9d9d0d890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerakan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_gerakan', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('filename_foto', sa.String(length=255), nullable=True),
    sa.Column('filename_video', sa.String(length=255), nullable=True),
    sa.Column('filename_model_tflite', sa.String(length=255), nullable=True),
    sa.Column('created_by_terapis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_terapis_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gerakan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gerakan_nama_gerakan'), ['nama_gerakan'], unique=False)

    op.create_table('program_rehabilitasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_program', sa.String(length=150), nullable=False),
    sa.Column('tanggal_program', sa.Date(), nullable=False),
    sa.Column('catatan_terapis', sa.Text(), nullable=True),
    sa.Column('terapis_id', sa.Integer(), nullable=True),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terapis_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_gerakan_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('gerakan_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_repetisi', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerakan_id'], ['gerakan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['program_rehabilitasi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_gerakan_detail')
    op.drop_table('program_rehabilitasi')
    with op.batch_alter_table('gerakan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gerakan_nama_gerakan'))

    op.drop_table('gerakan')
    # ### end Alembic commands ###
