"""Add User and PatientProfile tables for health app

Revision ID: 9ba9d9d0d890
Revises: ccdb91998948
Create Date: 2025-06-05 14:49:23.902061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba9d9d0d890'
down_revision = 'ccdb91998948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nama_pendamping', sa.String(length=120), nullable=True),
    sa.Column('tinggi_badan', sa.Integer(), nullable=True),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('golongan_darah', sa.String(length=5), nullable=True),
    sa.Column('riwayat_medis', sa.Text(), nullable=True),
    sa.Column('riwayat_alergi', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('produk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produk',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('harga', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('produk_pkey'))
    )
    op.drop_table('patient_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
