"""Initial migration for new local PostgreSQL database

Revision ID: decac81f8371
Revises: 
Create Date: 2025-06-21 10:09:31.381583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decac81f8371'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_username'), ['username'], unique=True)

    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('point_threshold', sa.Integer(), nullable=False),
    sa.Column('filename_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('point_threshold')
    )
    op.create_table('gerakan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_gerakan', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('blob_name_foto', sa.String(length=255), nullable=True),
    sa.Column('blob_name_video', sa.String(length=255), nullable=True),
    sa.Column('gcs_uri_model_tflite', sa.String(length=255), nullable=True),
    sa.Column('created_by_terapis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_terapis_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gerakan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gerakan_nama_gerakan'), ['nama_gerakan'], unique=False)

    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nama_pendamping', sa.String(length=120), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('catatan_tambahan', sa.Text(), nullable=True),
    sa.Column('tinggi_badan', sa.Integer(), nullable=True),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('golongan_darah', sa.String(length=5), nullable=True),
    sa.Column('riwayat_medis', sa.Text(), nullable=True),
    sa.Column('riwayat_alergi', sa.Text(), nullable=True),
    sa.Column('filename_foto_profil', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor_telepon'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pola_makan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.Column('terapis_id', sa.Integer(), nullable=True),
    sa.Column('tanggal_makan', sa.Date(), nullable=False),
    sa.Column('menu_pagi', sa.Text(), nullable=True),
    sa.Column('menu_siang', sa.Text(), nullable=True),
    sa.Column('menu_malam', sa.Text(), nullable=True),
    sa.Column('cemilan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terapis_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pola_makan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pola_makan_tanggal_makan'), ['tanggal_makan'], unique=False)

    op.create_table('program_rehabilitasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_program', sa.String(length=150), nullable=False),
    sa.Column('tanggal_program', sa.Date(), nullable=False),
    sa.Column('catatan_terapis', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BELUM_DIMULAI', 'BERJALAN', 'SELESAI', 'DIBATALKAN', name='programstatus'), nullable=False),
    sa.Column('terapis_id', sa.Integer(), nullable=True),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terapis_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_rehabilitasi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_rehabilitasi_status'), ['status'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='_user_badge_uc')
    )
    op.create_table('laporan_rehabilitasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_rehabilitasi_id', sa.Integer(), nullable=True),
    sa.Column('pasien_id', sa.Integer(), nullable=False),
    sa.Column('terapis_id', sa.Integer(), nullable=True),
    sa.Column('tanggal_laporan', sa.Date(), nullable=False),
    sa.Column('total_waktu_rehabilitasi_detik', sa.Integer(), nullable=True),
    sa.Column('catatan_pasien_laporan', sa.Text(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasien_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_rehabilitasi_id'], ['program_rehabilitasi.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['terapis_id'], ['app_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laporan_rehabilitasi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laporan_rehabilitasi_pasien_id'), ['pasien_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laporan_rehabilitasi_program_rehabilitasi_id'), ['program_rehabilitasi_id'], unique=False)

    op.create_table('program_gerakan_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('gerakan_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_repetisi', sa.Integer(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerakan_id'], ['gerakan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['program_rehabilitasi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laporan_gerakan_hasil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laporan_rehabilitasi_id', sa.Integer(), nullable=False),
    sa.Column('gerakan_id', sa.Integer(), nullable=True),
    sa.Column('program_gerakan_detail_id_asli', sa.Integer(), nullable=True),
    sa.Column('urutan_gerakan_dalam_program', sa.Integer(), nullable=True),
    sa.Column('jumlah_sempurna', sa.Integer(), nullable=True),
    sa.Column('jumlah_tidak_sempurna', sa.Integer(), nullable=True),
    sa.Column('jumlah_tidak_terdeteksi', sa.Integer(), nullable=True),
    sa.Column('waktu_aktual_per_gerakan_detik', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerakan_id'], ['gerakan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['laporan_rehabilitasi_id'], ['laporan_rehabilitasi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_gerakan_detail_id_asli'], ['program_gerakan_detail.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan_gerakan_hasil')
    op.drop_table('program_gerakan_detail')
    with op.batch_alter_table('laporan_rehabilitasi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laporan_rehabilitasi_program_rehabilitasi_id'))
        batch_op.drop_index(batch_op.f('ix_laporan_rehabilitasi_pasien_id'))

    op.drop_table('laporan_rehabilitasi')
    op.drop_table('user_badges')
    with op.batch_alter_table('program_rehabilitasi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_rehabilitasi_status'))

    op.drop_table('program_rehabilitasi')
    with op.batch_alter_table('pola_makan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pola_makan_tanggal_makan'))

    op.drop_table('pola_makan')
    op.drop_table('patient_profiles')
    with op.batch_alter_table('gerakan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gerakan_nama_gerakan'))

    op.drop_table('gerakan')
    op.drop_table('badges')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_username'))
        batch_op.drop_index(batch_op.f('ix_app_users_role'))
        batch_op.drop_index(batch_op.f('ix_app_users_email'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
