# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - be-restro-api

on:
  push:
    branches:
      - main # Anda bisa tambahkan branch lain jika diperlukan (misal: develop)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Pastikan versi Python ini sama dengan yang di App Service

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_89B1EA6FC8A7461F8452A0B63808CE6D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C363485F2C2642C38010965BB0B371C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A83469A03A344DF8AA3A88543CB7D6A6 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'be-restro-api' # Ganti dengan nama App Service Anda jika berbeda
          slot-name: 'Production'
          # Jika Anda mengunggah file zip, Anda perlu menyertakan package: 'release.zip'
          # Jika tidak, biarkan kosong untuk default yang mengambil dari root repo

      # --- LANGKAH BARU: Jalankan Migrasi Database ---
      # Langkah ini akan dijalankan setelah deployment kode selesai
      - name: 'Run Database Migrations'
        uses: azure/cli@v1 # Menggunakan Azure CLI untuk menjalankan perintah SSH di App Service
        with:
          inlineScript: |
            # Menggunakan `az webapp ssh` untuk terhubung dan menjalankan perintah
            # Pastikan Anda sudah mengizinkan koneksi SSH di App Service (biasanya default)
            # Dan Anda telah mengaktifkan "Allow Azure services to access this server" di database PostgreSQL Anda
            echo "Attempting to run database migrations..."
            az webapp ssh --name 'be-restro-api' --resource-group 'RG-RestroApp' --command "source /antenv/bin/activate && flask db upgrade" # Ganti dengan nama Resource Group Anda
            echo "Database migrations command sent."
            # Catatan: Perintah ini mungkin tidak menunjukkan output langsung dari migrasi
            # Anda bisa memeriksa log App Service untuk detail lebih lanjut

          # -- CATATAN PENTING UNTUK RESOURCE GROUP --
          # Ganti '<Nama_Resource_Group_Anda>' di atas dengan nama Resource Group Azure Anda.
          # Anda bisa menemukannya di Azure Portal, di Overview App Service Anda.

      # --- Opsional: Pastikan App Service dimulai ulang jika migrasi mengubah dependensi ---
      # Beberapa kasus membutuhkan restart eksplisit setelah migrasi besar
      - name: 'Restart App Service (Optional but Recommended)'
        run: |
          az webapp restart --name 'be-restro-api' --resource-group 'RG-RestroApp' # Ganti dengan nama Resource Group Anda
        uses: azure/cli@v1 # Menggunakan Azure CLI untuk menjalankan perintah restart

